
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SEF_HR_APP;

import SEF_HR_APP.frontend.MainLogin;

public class App {

    public static void main(String[] args) {

        MainLogin.main(args);
    }
}
