
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SEF_HR_APP;

public class App {

    public static void main(String[] args) {

        //System.out.println("Hello world!");
        MainLogin.main(args);

    }
}
